// Code generated by MockGen. DO NOT EDIT.
// Source: ./bidding/handler/bidding_handler.go

// Package handler is a generated GoMock package.
package handler

import (
	models "bidding-tracker/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBiddingServiceInterface is a mock of BiddingServiceInterface interface.
type MockBiddingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBiddingServiceInterfaceMockRecorder
}

// MockBiddingServiceInterfaceMockRecorder is the mock recorder for MockBiddingServiceInterface.
type MockBiddingServiceInterfaceMockRecorder struct {
	mock *MockBiddingServiceInterface
}

// NewMockBiddingServiceInterface creates a new mock instance.
func NewMockBiddingServiceInterface(ctrl *gomock.Controller) *MockBiddingServiceInterface {
	mock := &MockBiddingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBiddingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBiddingServiceInterface) EXPECT() *MockBiddingServiceInterfaceMockRecorder {
	return m.recorder
}

// GetBidsForItem mocks base method.
func (m *MockBiddingServiceInterface) GetBidsForItem(itemID string) ([]models.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBidsForItem", itemID)
	ret0, _ := ret[0].([]models.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBidsForItem indicates an expected call of GetBidsForItem.
func (mr *MockBiddingServiceInterfaceMockRecorder) GetBidsForItem(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBidsForItem", reflect.TypeOf((*MockBiddingServiceInterface)(nil).GetBidsForItem), itemID)
}

// GetItemsByUser mocks base method.
func (m *MockBiddingServiceInterface) GetItemsByUser(userID string) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsByUser", userID)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByUser indicates an expected call of GetItemsByUser.
func (mr *MockBiddingServiceInterfaceMockRecorder) GetItemsByUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByUser", reflect.TypeOf((*MockBiddingServiceInterface)(nil).GetItemsByUser), userID)
}

// GetWinningBid mocks base method.
func (m *MockBiddingServiceInterface) GetWinningBid(itemID string) (models.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWinningBid", itemID)
	ret0, _ := ret[0].(models.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWinningBid indicates an expected call of GetWinningBid.
func (mr *MockBiddingServiceInterfaceMockRecorder) GetWinningBid(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWinningBid", reflect.TypeOf((*MockBiddingServiceInterface)(nil).GetWinningBid), itemID)
}

// PlaceBid mocks base method.
func (m *MockBiddingServiceInterface) PlaceBid(itemID, userID string, amount float64) (models.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceBid", itemID, userID, amount)
	ret0, _ := ret[0].(models.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceBid indicates an expected call of PlaceBid.
func (mr *MockBiddingServiceInterfaceMockRecorder) PlaceBid(itemID, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceBid", reflect.TypeOf((*MockBiddingServiceInterface)(nil).PlaceBid), itemID, userID, amount)
}
