// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/repository.go

// Package repository is a generated GoMock package.
package repository

import (
	models "bidding-tracker/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuctionDB is a mock of AuctionDB interface.
type MockAuctionDB struct {
	ctrl     *gomock.Controller
	recorder *MockAuctionDBMockRecorder
}

// MockAuctionDBMockRecorder is the mock recorder for MockAuctionDB.
type MockAuctionDBMockRecorder struct {
	mock *MockAuctionDB
}

// NewMockAuctionDB creates a new mock instance.
func NewMockAuctionDB(ctrl *gomock.Controller) *MockAuctionDB {
	mock := &MockAuctionDB{ctrl: ctrl}
	mock.recorder = &MockAuctionDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuctionDB) EXPECT() *MockAuctionDBMockRecorder {
	return m.recorder
}

// GetBidsByItem mocks base method.
func (m *MockAuctionDB) GetBidsByItem(itemID string) ([]models.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBidsByItem", itemID)
	ret0, _ := ret[0].([]models.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBidsByItem indicates an expected call of GetBidsByItem.
func (mr *MockAuctionDBMockRecorder) GetBidsByItem(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBidsByItem", reflect.TypeOf((*MockAuctionDB)(nil).GetBidsByItem), itemID)
}

// GetItemsByUser mocks base method.
func (m *MockAuctionDB) GetItemsByUser(userID string) ([]models.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsByUser", userID)
	ret0, _ := ret[0].([]models.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByUser indicates an expected call of GetItemsByUser.
func (mr *MockAuctionDBMockRecorder) GetItemsByUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByUser", reflect.TypeOf((*MockAuctionDB)(nil).GetItemsByUser), userID)
}

// GetWinningBid mocks base method.
func (m *MockAuctionDB) GetWinningBid(itemID string) (models.Bid, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWinningBid", itemID)
	ret0, _ := ret[0].(models.Bid)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWinningBid indicates an expected call of GetWinningBid.
func (mr *MockAuctionDBMockRecorder) GetWinningBid(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWinningBid", reflect.TypeOf((*MockAuctionDB)(nil).GetWinningBid), itemID)
}

// RecordBidForItem mocks base method.
func (m *MockAuctionDB) RecordBidForItem(bid models.Bid) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBidForItem", bid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordBidForItem indicates an expected call of RecordBidForItem.
func (mr *MockAuctionDBMockRecorder) RecordBidForItem(bid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBidForItem", reflect.TypeOf((*MockAuctionDB)(nil).RecordBidForItem), bid)
}
